### ISSUE TITLE
Merge to FlexGet

### ISSUE THREAD

**Issue by paranoidi** [nikdoof/flexget-twitter#1]
This looks pretty cool, why don't you fork FlexGet and add this to the package. Then send us pull request when you're done and we'll integrate your work into the collective :). 

Some additional documentation in the plugin would be nice, also try to avoid any PEP8 violations (if you fork, you can use bin/paver pep8 to check them).

**Comment by nikdoof** [comment]
Started the process in [pull #564](https://github.com/Flexget/Flexget/pull/564)
