### ISSUE TITLE
Does flexget-twitter work with flexget 1.2?

### ISSUE THREAD

**Issue by minerva330** [nikdoof/flexget-twitter#4]
I tried to install your plugin but I have not been able to get it to work? Is this still an active plug-in? I ask because when I brought-up my issue on the flexget forum (http://flexget.com/ticket/2606) it was suggested that the API needs to be updated to flexget 1.2

**Comment by nikdoof** [comment]
See [pull #564](https://github.com/Flexget/Flexget/pull/564)
